# Generated by Django 4.1.4 on 2022-12-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_pessoa_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Pedido',
        ),
    ]
