# Generated by Django 4.1.5 on 2023-01-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_pedido_delete_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numeroMesa',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
