# Generated by Django 4.1.5 on 2023-01-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_pedido_numero_alter_pedido_numeromesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='imagem',
            field=models.ImageField(default=None, upload_to=None),
        ),
    ]
