# Generated by Django 4.1.5 on 2023-01-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_pessoa_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numeroMesa',
            field=models.IntegerField(default=None),
        ),
    ]
